### PR TITLE
DOC: shorten the top-level `README.rst` file

### PR DESCRIPTION
**Pull request by mrakitin**
Mostly all useful documentation was ported to the Sphinx docs via #57. Let me know if you'd like to keep anything from the old docs (like a picture of the "basic" beamline or a Vagrant installation instructions).

### CODE REVIEW

**Review by jklynch — APPROVED** [review]

**Review by AbbyGi — APPROVED** [review]

**Comment by mrakitin** [comment]
Thanks, @jklynch, I am done with my changes for now, unless people have concerns.

**Comment by mrakitin** [comment]
Maybe we still want this information in the documentation?
> -  (OPTIONAL) Make sure you have `mongodb`_ installed and the service is
   running (see `local.yml`_ for details)

**Review by jennmald — APPROVED** [review]

**Comment by mrakitin** [comment]
OK, in the process of adding the information about `local.yml` databroker config.

**Comment by mrakitin** [comment]
Tested my changes from the latest commit, the docs built successfully, and now we have this subsection:
image

I am a little worried about referencing the `local.yml` file - the link points to the right file in the file system, but may fail once published to github.io. But we can fix it later, and moreover, we have the file's contents available in the docs.

**Comment by mrakitin** [comment]
OK, I am going to go ahead and merge it - the changes seem trivial.

**Comment by mrakitin** [comment]
I noticed an issue with the URL as I expected (points to the non-existent target https://nsls-ii.github.io/examples/local.yml), that's why I committed the fix via https://github.com/NSLS-II/sirepo-bluesky/commit/9b01c2138502955b64f98cd58387653c7a1a50b1.

**Pull request merged**
