### PR TITLE
New API: source reports

### PR DESCRIPTION
**Pull request by mrakitin**

### CODE REVIEW

**Comment by mrakitin** [comment]
@thomaswmorris, I know that you were using this PR branch. I rebased on `master` to resolve merge conflicts caused by updates in https://github.com/NSLS-II/sirepo-bluesky/pull/73. You can get the latest version with:
```bash
$ git reset --hard mrakitin-fork/new-api-source-reports
```
(make sure you have your uncommitted changes saved somewhere before doing it)

**Comment by mrakitin** [comment]
@thomaswmorris, @AbbyGi, @awalter-bnl, do you have any comments/suggestions? I plan to merge it by the end of the week.

**Review by thomaswmorris — COMMENTED** [review]
This all looks good, and I don't think it conflicts with my local SB.

**Review by awalter-bnl — APPROVED** [review]
This looks good to me @mrakitin, there are some 'changes' that do not appear to be changes (particualrly in the test_bl_elements_as_ophyd_objs.py) file but I suspect they are due to the rebase !-).

good to merge on my end.

**Comment by mrakitin** [comment]
Thanks, @thomaswmorris and @awalter-bnl for your reviews!

@awalter-bnl, regarding the updates in `sirepo_bluesky/tests/test_bl_elements_as_ophyd_objs.py`: we added this condition `if "element_position" in v.component_names:` to fix the issues introduced by the new code.

**Pull request merged**
