### PR TITLE
DOC: use cloud theme for Sphinx

### PR DESCRIPTION
**Pull request by mrakitin**
This PR switches the docs theme to https://cloud-sptheme.readthedocs.io (inspired by https://psicode.org/psi4manual/master/). The new theme provides a bit more compact layout/text, and feels more modern.

### Before
Screenshot 2022-09-15 at 03-55-44 sirepo-bluesky Documentation — sirepo-bluesky 0 post1 gf685ea9 documentation

### After
Screenshot 2022-09-15 at 03-58-18 sirepo-bluesky Documentation — sirepo-bluesky 0 4 3 post41 dev0 g05be2df documentation

Closes https://github.com/NSLS-II/sirepo-bluesky/issues/58.

### CODE REVIEW

**Comment by mrakitin** [comment]
@AbbyGi, @thomaswmorris, @jklynch, ready for your review.

I fixed the version displayed on the generated pages via checking out the code in the corresponding CI workflows with `fetch-depth: 0` (not needed everywhere, just in the workflows for docs and publishing).

Also, the artifact with the built docs is available at https://github.com/NSLS-II/sirepo-bluesky/actions/runs/3085895561.

**Comment by thomaswmorris** [comment]
Looks good! I like the style

**Review by AbbyGi — APPROVED** [review]

**Review by thomaswmorris — APPROVED** [review]

**Comment by mrakitin** [comment]
Thanks for your reviews! I'll merge it now.

**Comment by mrakitin** [comment]
The docs in new style are live!
https://nsls-ii.github.io/sirepo-bluesky/index.html

**Pull request merged**
