### PR TITLE
TST: Removed detector tests due to ophyd update

### PR DESCRIPTION
**Pull request by rlb131**
The new ophyd update removed support for storing non-numerical values in the SynAxis class, making these tests now fail.

### CODE REVIEW

**Review by jklynch — CHANGES_REQUESTED** [review]
It makes sense to remove tests for a feature that has been removed, but is that the case here? It would be best to fix the tests if that's possible.

**Comment by mrakitin** [comment]
@rlb131, @jklynch, I've just posted the motivation for this work: https://github.com/NSLS-II/sirepo-bluesky/issues/123. Riley submitted this PR per my request. Sorry that I did not summarize why we needed it earlier.

The reason for test failures is that in the latest releases of `event-model` (v1.9.3+), `bluesky` (v1.11.0), and `ophyd` (v1.8.0) stricter checks are being applied to the data types. The test failures occur only for the old API code base. It's a good time to address the deprecation/removal of the old API.

Earlier, we removed the failing examples in the documentation (#118, commit https://github.com/NSLS-II/sirepo-bluesky/pull/118/commits/6493bdc85864955a2306923af115e9ac54c122d8).

**Comment by mrakitin** [comment]
@rlb131, do you mind also removing the referred code modules in #123? Thanks!

**Comment by mrakitin** [comment]
@AbbyGi, @thomaswmorris, @jklynch, are you OK with the removal of the old API?

**Pull request merged**
